name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Kubernetes

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/manifests/namespace.yaml || true  # in case namespace already exists
        kubectl apply -f k8s/manifests/backend-deployment.yaml
        kubectl apply -f k8s/manifests/backend-svc.yaml
        kubectl apply -f k8s/manifests/frontend-deployment.yaml
        kubectl apply -f k8s/manifests/frontend-svc.yaml
