name: Dev CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: repo/image
          tags: v1, latest
          registry: registry-url.io
          dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build Backend
        run: docker build -t faruq96/my-backend:latest -f cmd/Dockerfile .

      - name: Push Backend Image
        run: docker push faruq96/my-backend:latest

      - name: Build Frontend
        run: docker build -t faruq96/my-frontend:latest -f web/Dockerfile web

      - name: Push Frontend Image
        run: docker push faruq96/my-frontend:latest

      - name: Success Confirmation
        run: echo "Build and push completed successfully!"
